#!/bin/sh

# shellcheck disable=SC2028
echo "Running detekt..."
./gradlew detekt
EXIT_CODE=$?
if [ $EXIT_CODE -ne 0 ]; then
  echo $OUTPUT
  echo "***********************************************"
  echo "                 Detekt failed                 "
  echo " Please fix the above issues before committing "
  echo "***********************************************"
  exit $EXIT_CODE
fi

echo "Executing unit test..."
./gradlew testDebugUnitTest
# shellcheck disable=SC2039
if [ $? == 1 ]; then
  echo "Test failed."
  exit 1
else
  echo "Test passed!"
fi